BEGIN

CREATE TABLE SALE_INVOICES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    NUMBER VARCHAR(50),
    SUBTOTAL DECIMAL(10, 2),
    SERVICE_FEE DECIMAL(10, 2),
    PAYMENT_FEE DECIMAL(10, 2),
    DISCOUNT DECIMAL(10, 2),
    VAT DECIMAL(10, 2),
    TOTAL DECIMAL(10, 2),
    STATUS VARCHAR(50),
    TRANSACTION_AT DATETIME,
    DUE_AT DATETIME,
    COMPLETED_AT DATETIME,
    CANCELED_AT DATETIME,
    EXPIRED_AT DATETIME,
    REJECTED_AT DATETIME,
    REFUNDED_AT DATETIME,
    METADATA JSON,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

END;