BEGIN

CREATE TABLE OTPS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    USER_ID INTEGER,
    ACTION VARCHAR(50),
    CODE VARCHAR(10),
    STATUS VARCHAR(20),
    SENT_AT DATETIME,
    VERIFIED_AT DATETIME,
    EXPIRED_AT DATETIME,
    VERIFY_ATTEMPTS INTEGER DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

END;