BEGIN

CREATE TABLE TICKET_APPROVALS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    REGISTERED_EVENT_ID INTEGER NOT NULL,
    METADATA JSON,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

END;