BEGIN

CREATE TABLE TICKETS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EVENT_ID INTEGER NOT NULL,
    CATEGORY VARCHAR(100),
    PRICE DECIMAL(10, 2),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);


END;