BEGIN

CREATE TABLE SALE_INVOICE_ITEMS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SALE_INVOICE_ID INTEGER NOT NULL,
    INVOICEABLE_ID INTEGER,
    INVOICEABLE_TYPE VARCHAR(50),
    QTY INTEGER,
    TOTAL DECIMAL(10, 2),
    METADATA JSON,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

END;